### PR TITLE
Added Padding

### PR DESCRIPTION
**Pull request by vednp**
Resolved Issue #154

Added padding of pt-24 to top
Also added a little padding to the title and subtitle to look good as they had 0 margins

### CODE REVIEW

**Comment by AnnikenYT** [comment]
Hey! Thank you for contributing to Bergflix.! If you have a Bergflix. Account, you can earn an account badge by contributing.
If you want to receive this badge, please comment the name of your Bergflix. Account, or contact me on [discord](https://bflx.de/discord).

~ Anniken ❤️
> _(Saved Reply)_

**Review by AnnikenYT — APPROVED** [review]

**Comment by vednp** [comment]
Hey @AnnikenYT can I ask why this isn't merged yet?
Does my code need more improvements?

**Comment by AnnikenYT** [comment]
No, GitHub actions just isn't doing its thing 😅

**Comment by AnnikenYT** [comment]
I merged it manually, should be deployed to production in a few minutes

**Comment by vednp** [comment]
I used your website it's great 
Keep it up buddy 👍

**Pull request merged**
